import type { SymbolMeta } from "./types";

/**
 * Tradable universe. Started as CME futures; now spans crypto, FX, and
 * equities. (The export keeps its original name — it is imported widely.)
 */
export const FUTURES_SYMBOLS: SymbolMeta[] = [
  {
    symbol: "NQ",
    name: "E-mini NASDAQ 100",
    exchange: "CME",
    category: "index",
    tickSize: 0.25,
    tickValue: 5,
    pointValue: 20,
    decimals: 2,
    basePrice: 21480,
    volatility: 14,
  },
  {
    symbol: "ES",
    name: "E-mini S&P 500",
    exchange: "CME",
    category: "index",
    tickSize: 0.25,
    tickValue: 12.5,
    pointValue: 50,
    decimals: 2,
    basePrice: 6085,
    volatility: 3.4,
  },
  {
    symbol: "MNQ",
    name: "Micro E-mini NASDAQ 100",
    exchange: "CME",
    category: "index",
    tickSize: 0.25,
    tickValue: 0.5,
    pointValue: 2,
    decimals: 2,
    basePrice: 21480,
    volatility: 14,
  },
  {
    symbol: "MES",
    name: "Micro E-mini S&P 500",
    exchange: "CME",
    category: "index",
    tickSize: 0.25,
    tickValue: 1.25,
    pointValue: 5,
    decimals: 2,
    basePrice: 6085,
    volatility: 3.4,
  },
  {
    symbol: "YM",
    name: "E-mini Dow",
    exchange: "CBOT",
    category: "index",
    tickSize: 1,
    tickValue: 5,
    pointValue: 5,
    decimals: 0,
    basePrice: 44250,
    volatility: 22,
  },
  {
    symbol: "RTY",
    name: "E-mini Russell 2000",
    exchange: "CME",
    category: "index",
    tickSize: 0.1,
    tickValue: 5,
    pointValue: 50,
    decimals: 1,
    basePrice: 2310,
    volatility: 2.4,
  },
  {
    symbol: "CL",
    name: "Crude Oil",
    exchange: "NYMEX",
    category: "energy",
    tickSize: 0.01,
    tickValue: 10,
    pointValue: 1000,
    decimals: 2,
    basePrice: 71.4,
    volatility: 0.22,
  },
  {
    symbol: "GC",
    name: "Gold",
    exchange: "COMEX",
    category: "metals",
    tickSize: 0.1,
    tickValue: 10,
    pointValue: 100,
    decimals: 1,
    basePrice: 3348,
    volatility: 4.2,
  },
  {
    symbol: "BTC",
    name: "Bitcoin / USD",
    exchange: "CRYPTO",
    category: "crypto",
    tickSize: 1,
    tickValue: 1,
    pointValue: 1,
    decimals: 0,
    basePrice: 112400,
    volatility: 220,
  },
  {
    symbol: "ETH",
    name: "Ether / USD",
    exchange: "CRYPTO",
    category: "crypto",
    tickSize: 0.1,
    tickValue: 0.1,
    pointValue: 1,
    decimals: 1,
    basePrice: 4120,
    volatility: 11,
  },
  {
    symbol: "EURUSD",
    name: "Euro / US Dollar",
    exchange: "FX",
    category: "fx",
    tickSize: 0.0001,
    tickValue: 10,
    pointValue: 100000,
    decimals: 4,
    basePrice: 1.0885,
    volatility: 0.0009,
  },
  {
    symbol: "GBPUSD",
    name: "British Pound / US Dollar",
    exchange: "FX",
    category: "fx",
    tickSize: 0.0001,
    tickValue: 10,
    pointValue: 100000,
    decimals: 4,
    basePrice: 1.2705,
    volatility: 0.0012,
  },
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    exchange: "NASDAQ",
    category: "equity",
    tickSize: 0.01,
    tickValue: 0.01,
    pointValue: 1,
    decimals: 2,
    basePrice: 246.3,
    volatility: 0.9,
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    exchange: "NASDAQ",
    category: "equity",
    tickSize: 0.01,
    tickValue: 0.01,
    pointValue: 1,
    decimals: 2,
    basePrice: 328.5,
    volatility: 3.1,
  },
];

export const DEFAULT_WATCHLIST = ["NQ", "ES", "MNQ", "MES"];
