import type { SymbolMeta } from "./types";

/** CME futures universe supported at launch. */
export const FUTURES_SYMBOLS: SymbolMeta[] = [
  {
    symbol: "NQ",
    name: "E-mini NASDAQ 100",
    exchange: "CME",
    category: "index",
    tickSize: 0.25,
    tickValue: 5,
    pointValue: 20,
    decimals: 2,
    basePrice: 21480,
    volatility: 14,
  },
  {
    symbol: "ES",
    name: "E-mini S&P 500",
    exchange: "CME",
    category: "index",
    tickSize: 0.25,
    tickValue: 12.5,
    pointValue: 50,
    decimals: 2,
    basePrice: 6085,
    volatility: 3.4,
  },
  {
    symbol: "MNQ",
    name: "Micro E-mini NASDAQ 100",
    exchange: "CME",
    category: "index",
    tickSize: 0.25,
    tickValue: 0.5,
    pointValue: 2,
    decimals: 2,
    basePrice: 21480,
    volatility: 14,
  },
  {
    symbol: "MES",
    name: "Micro E-mini S&P 500",
    exchange: "CME",
    category: "index",
    tickSize: 0.25,
    tickValue: 1.25,
    pointValue: 5,
    decimals: 2,
    basePrice: 6085,
    volatility: 3.4,
  },
  {
    symbol: "YM",
    name: "E-mini Dow",
    exchange: "CBOT",
    category: "index",
    tickSize: 1,
    tickValue: 5,
    pointValue: 5,
    decimals: 0,
    basePrice: 44250,
    volatility: 22,
  },
  {
    symbol: "RTY",
    name: "E-mini Russell 2000",
    exchange: "CME",
    category: "index",
    tickSize: 0.1,
    tickValue: 5,
    pointValue: 50,
    decimals: 1,
    basePrice: 2310,
    volatility: 2.4,
  },
  {
    symbol: "CL",
    name: "Crude Oil",
    exchange: "NYMEX",
    category: "energy",
    tickSize: 0.01,
    tickValue: 10,
    pointValue: 1000,
    decimals: 2,
    basePrice: 71.4,
    volatility: 0.22,
  },
  {
    symbol: "GC",
    name: "Gold",
    exchange: "COMEX",
    category: "metals",
    tickSize: 0.1,
    tickValue: 10,
    pointValue: 100,
    decimals: 1,
    basePrice: 3348,
    volatility: 4.2,
  },
];

export const DEFAULT_WATCHLIST = ["NQ", "ES", "MNQ", "MES"];
